# Generated by Django 5.0.3 on 2024-03-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzez', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
