# Generated by Django 5.0.3 on 2024-03-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzez', '0003_course_quizquestions_quizchoices_quizzes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_price',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
