# Generated by Django 5.0.3 on 2024-03-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzez', '0004_alter_course_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_offer_price',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
